version: "3"

services:
  api:
    image: michaelmackend/ctci_api_2_1:v2
    networks:
      - traefik_public
    deploy:
      replicas: 1
      labels:
        - "traefik.backend=ctci_2_1_api"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefixStrip:/ctci/2.1/;Method:POST"
        - "traefik.docker.network=traefik_public"
  web:
    image: michaelmackend/ctci_web_2_1:v2
    networks:
      - traefik_public
    deploy:
      replicas: 1
      labels:
        - "traefik.backend=ctci_2_1_web"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefixStrip:/ctci/2.1/;Method:GET"
        - "traefik.docker.network=traefik_public"
networks:
  traefik_public:
    external: true

