version: "3"

services:
  app:
    image: michaelmackend/ctci_1_4:v1
    networks:
      - traefik_public
    deploy:
      replicas: 1
      labels:
        - "traefik.backend=ctci_1_4_app"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefixStrip:/ctci/1.4/;Method:POST"
        - "traefik.docker.network=traefik_public"
  web:
    image: michaelmackend/ctci_web_1_4:v1
    networks:
      - traefik_public
    deploy:
      replicas: 1
      labels:
        - "traefik.backend=ctci_1_4_web"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefixStrip:/ctci/1.4/;Method:GET"
        - "traefik.docker.network=traefik_public"
networks:
  traefik_public:
    external: true

