version: "3"

services:
  app:
    image: michaelmackend/ctci_1_1:v2.1
    networks: 
      - traefik_public
    deploy:
      replicas: 1
      labels:
        - "traefik.backend=ctci_1_1_app"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefixStrip:/ctci/1.1/;Method:POST"
        - "traefik.docker.network=traefik_public"
  web:
    image: michaelmackend/ctci_web_1_1:v2.3
    networks:
      - traefik_public
    deploy:
      replicas: 1
      labels:
        - "traefik.backend=ctci_1_1_web"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefixStrip:/ctci/1.1/;Method:GET"
        - "traefik.docker.network=traefik_public"
networks:
  traefik_public:
    external: true

